spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/td_writting?characterEncoding=utf8
    username: root
    password: 123456
    #最大活跃数
    maxActive: 20
    #初始化数量
    initiaSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个PSCache的大小
    poolPrepareStatements: true
    maxPoolPrepareStatementPerConnectionSize: 20
    minIdle: 1
    timeBetweenEvictionRunsMillis:  60000
    minEvictableIdleTimeMillis: 300000
    validationQuery:  select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat, wall, log4j
  thymeleaf:
    cache: false
  freemarker:
    cache: false
  groovy:
    template:
      cache: false
  velocity:
    cache: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wust.lesson.study.model


# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
